### PR TITLE
Add stats for some batteries

### PR DESCRIPTION
**Pull request by Quantumshark**
Images and descriptions TBD

### CODE REVIEW

**Comment by 3agleEmpire** [comment]
Will Be Merged Later On When We have Battery Outfit Sprites.

**Comment by TheSlavWolf** [comment]
Well, if the Lupainians are energy weapon freaks, they need LARGE batteries.

**Comment by KimDare75** [comment]
> Will Be Merged Later On When We have Battery Outfit Sprites.

Uuuh...
Do we have a **specific** art-style yet? If not, I might suggest a kind of _stealthy_ one...
(I am asking because I heard of stealth mechanics requests on the main ES github. This might be a chance to add cool new mechanics to the game and the Lupainians, making them relevant in tech. Wolves are stealthy.)

**Comment by mOctave** [comment]
https://github.com/3agleEmpire/Lupainian-Development/pull/12 <- Battery outfit sprites!

**Pull request merged**
